name: TEST RELEASE TXT

on:
  workflow_dispatch:

permissions: # 1. Esto es vital para que el Action pueda escribir la Release
  contents: write

env:
  pkgver: 1.1
  pkgurl: "https://github.com/"

jobs:
  make-txt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Generar archivo"
        run: echo "Este es un test para el flujo del AUR" > test.txt

      - name: "Subir archivos como Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: kernel-binaries # Nombre del "paquete" temporal
          path: |
            test.txt
          retention-days: 1 # Se borra solo después de 1 día (ahorro de espacio)

  up-to-aur:
    needs: make-txt
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: 1 - Install git base-devel and sudo
        run: pacman -Syu --noconfirm git base-devel sudo pacman-contrib openssh

      - name: Checkout linux-tkg
        uses: actions/checkout@v4

      - name: "Descargar Artifacts del Job anterior"
        uses: actions/download-artifact@v4
        with:
          name: kernel-binaries
          path: . # Los pone en esta carpeta

      - name: 2 - Create user
        run: |
          useradd user -m -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Set val in PKGBUILD
        run: |
          chown -R user:user .
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/download/test-aur-${{ github.run_number }}/test.txt"
          sed -i "s|PKGVER|1|" PKGBUILD
          sed -i "s|PKGURL|${{ env.pkgurl }}|" PKGBUILD
          sed -i "s|KERNEL_URL|$RELEASE_URL|" PKGBUILD

      - name: config aur
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          # Configurar usuario de Git
          git config --global user.name "Lautaro"
          git config --global user.email "${{secrets.MAIL}}"

      - name: workflow
        run: |
          # 1. Permisos iniciales (como root)
          chown -R user:user .
          
          # 2. Todo el bloque de comandos ejecutado por 'user'
          su - user <<'EOF'
            # Ahora estamos dentro del contexto de 'user'
            git clone ssh://aur@aur.archlinux.org/test.git
            cp PKGBUILD test/
            cd test
            
            # Comandos de Arch
            updpkgsums
            makepkg --printsrcinfo > .SRCINFO
            
            # Configurar Git y Subir
            git config --global user.name "Lauta-dev"
            git config --global user.email "${{secrets.MAIL}}"
            git add PKGBUILD .SRCINFO
            git commit -m "Actualización v$GITHUB_RUN_NUMBER"
            git push origin master
          EOF
      
      - name: "Publicar Release"
        uses: softprops/action-gh-release@v2
        with:
          # 2. Los tags no deben llevar espacios, mejor usar guiones
          tag_name: "test-aur-${{ github.run_number }}"
          name: "Build #${{ github.run_number }}"
          files: test.txt
          # 3. Opcional: marcar como prerelease si solo es un test
          prerelease: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

